export const NavUrl = {
    LOGIN: "LOGIN" as "LOGIN",
    REGISTER: "REGISTER" as "REGISTER",
    FORGET_PASSWORD: "FORGET_PASSWORD" as "FORGET_PASSWORD",
    RESET_PASSWORD: "RESET_PASSWORD" as "RESET_PASSWORD",
    HOME: "HOME" as "HOME",
}
